# DATA SCIENCE DAY (1 - 10)

# PYTHON BASICS

In [1]:
n = 10

if n >0:
    print(True)
else:
    print(False)

True


In [3]:
a = 5
b = 10
if a>b:
    print("a is positive")
elif a==b:
    print("Both are equal")
else:
    print("a is negative")

a is negative


In [4]:
tuple = (1,2,3,4)  #iterating through tuple
for tuple in tuple:
  print(tuple)

1
2
3
4


In [2]:
tuple = ("mouse", [8, 4, 6], (1, 2, 3))
print(tuple)
tuple[1][0]=5
print(tuple)             #tuple is immutable but its elements can be both mutable and immutable 
                        #Can make changes to mutable objects  

('mouse', [8, 4, 6], (1, 2, 3))
('mouse', [5, 4, 6], (1, 2, 3))


In [4]:
languages = {'React', 'Java', 'Python'}

print('before:',languages)
removedValue = languages.discard('Java')
print('after:', languages)
print(removedValue)

before: {'Python', 'Java', 'React'}
after: {'Python', 'React'}
None


In [12]:
mydict = {1:'a', 2:'b', 5:'c', 4:'d'}
print(mydict.items())
print(mydict.keys())
print(mydict.values())            #same for mydict name 

dict_items([(1, 'a'), (2, 'b'), (5, 'c'), (4, 'd')])
dict_keys([1, 2, 5, 4])
dict_values(['a', 'b', 'c', 'd'])


In [13]:
def row(n):
    if n < 1:
        return
    print("*", end=" ")
    row(n - 1)

def pattern(n):
    if n < 1:
        return
    row(n)
    print("")
    pattern(n - 1)

n = 5
pattern(n)

* * * * * 
* * * * 
* * * 
* * 
* 


In [14]:
def row(n):
    if n < 1:
        return
    for i in range(0,n):
        print("*",end=" ")

def pattern(n):
    if n < 1:
        return
    row(n)
    print("")
    pattern(n - 1)

n = 5
pattern(n)

* * * * * 
* * * * 
* * * 
* * 
* 


In [15]:
def row(n):
    if n < 1:
        return
    for i in range(n):
        print("*", end=" ")
    print("")             # This ensures a new line without adding extra spacing
                            #Each print() call adds a new line by default.

def pattern(n):
    if n < 1:
        return
    row(n)
    pattern(n - 1)

n = 5
pattern(n)


* * * * * 
* * * * 
* * * 
* * 
* 


In [17]:
def row(n):
    if n < 1:
        return
    for i in range(n):
        print("*", end=" ")


def pattern(n):
    if n < 1:
        return
    row(n)
    print("\n")               # New line after each row   #Adds a newline and then another implicit newline from print().
                                #Output: Moves the cursor to the next line and adds an extra line break 
    pattern(n - 1)

n = 5
pattern(n)


* * * * * 

* * * * 

* * * 

* * 

* 



In [6]:
def row(n):
    if n < 1:
        return
    for i in range(n):
        print("*", end=" ")
    print("\n", end="")  # Using \n

def pattern(n):
    if n < 1:
        return
    row(n)
    pattern(n - 1)

n = 5
pattern(n)

* * * * * 
* * * * 
* * * 
* * 
* 


In [1]:
class Voter:
    voting_age = 18
    num_voters = 0

    def __init__(self, age):
        self.age = age
        Voter.num_voters += 1

    @staticmethod
    def is_eligible(age):
        return age >= Voter.voting_age

    @classmethod
    def get_total_voters(cls):
        return cls.num_voters                       #cls short for class used to refer to class same as self refers to instance of a class
                                                        #cls is used to access class level data eg. it return the value of num_voters in class Voter. 

    def check_eligibility(self):
        if Voter.is_eligible(self.age):
            print(f"You are eligible to vote at age {self.age}.")
        else:
            print(f"Sorry, you are not eligible to vote at age {self.age}.")


# Create voter instances
voter1 = Voter(20)
voter2 = Voter(16)
voter3 = Voter(25)

# Check eligibility and total voters

voter1.check_eligibility()                # Output: You are eligible to vote at age 20.
voter2.check_eligibility()                # Output: Sorry, you are not eligible to vote at age 16.
voter3.check_eligibility()                # Output: You are eligible to vote at age 25.
print(f"Total voters: {Voter.get_total_voters()}")              # Output: Total voters: 3

You are eligible to vote at age 20.
Sorry, you are not eligible to vote at age 16.
You are eligible to vote at age 25.
Total voters: 3


# NUMPY BASICS 

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
a = np.insert(a, 2, 100)  # Update 'a' with the new array including the inserted element.
print(a)  # This will now print the modified array.

[  1   2 100   3   4   5]


In [3]:
import numpy as np               
a = np.array([1, 2, 3, 4, 5])    
np.insert(a, 2, 100)              # Insert the value 100 at index 2 of array 'a'.
print(a)                          # Print the modified array 'a'.

[1 2 3 4 5]


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()                      #copy() basically creates  a copy of it independent of the original , 
arr[0] = 42                                    #any changes done in original won't reflect back in copy

print(arr)
print(x)

import numpy as np            #view() is actually a way to see the data and changes on it reflects in the original 
                                # it actually used when you need to work on the data but a small portion of it. you want the changes u do would appear
                                #in the original but can't work with the whole data as it is massive.

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [1]:
# By default axis=0 ; concatenate by rows

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [2]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
# [1,2] and [3,4] are 2 elements of arr1
# [5,6] and [7,8] are 2 elements of arr2
#axis = 1 ; [1,2]+[5,6] and [3,4]+[7,8]

result = np.concatenate((arr1, arr2), axis=1)
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [4]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[10 40]
 [20 50]
 [30 60]]


In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])                  #concatenate simply merge two or more arrays in the existing dim.
                                            # no new dim array . no seperate arrays found they are merged.
arr2 = np.array([4, 5, 6])
np.concatenate((arr1, arr2))



array([1, 2, 3, 4, 5, 6])

In [6]:
np.stack((arr1, arr2), axis=0)                #stack bundled 2 arrays in one new array . Inside the stack the arrays are completely seperated.

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new = np.array_split(arr, 2)
print(new)

[array([1, 2, 3]), array([4, 5, 6])]


In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new = np.array_split(arr, 3)
print(new)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new = np.array_split(arr, 4)
print(new)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [8]:
import numpy as np                      #try to split in as many equal parts possible 
arr = np.array([1, 2, 3, 4, 5, 6])
new = np.array_split(arr, 5)
print(new)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [9]:
import numpy as np                      # either if there are some empty arrays as well 
arr = np.array([1, 2, 3, 4, 5, 6])
new = np.array_split(arr, 7)
print(new)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


In [10]:
import numpy as np

arr = np.array([3, 2, 0, 1])
arr1 = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))
print(np.sort(arr1))

[0 1 2 3]
['apple' 'banana' 'cherry']


In [11]:
import numpy as np

arr = np.array([3, 2, 0, 1])                             #sorting on the basis of low ASCII values for charecters
arr1 = np.array(['banana', 'Apple', 'apple'])

print(np.sort(arr))
print(np.sort(arr1))


[0 1 2 3]
['Apple' 'apple' 'banana']


# PANDAS BASICS 

In [12]:
import pandas as pd
lst = [['id', 'name', 'address'], [1, 2, 3, 4], ['A', 'B', 'C', 'D'], ['Aswin', 'Anil', 'Akil', 'Aman']]

#zip() - pairing of each element of the first list with the corresponding elements of the other list.
#and paired them in (,) like this
#eg. ('id',[1, 2, 3, 4])
#('name',['A', 'B', 'C', 'D'])
#('address',['Aswin', 'Anil', 'Akil', 'Aman'])

#dict((zip(lst[0], lst[1:])) - will create a dictionary as their key value pair...
#{'id':[1, 2, 3, 4] , 'name':['A', 'B', 'C', 'D'] , 'address':['Aswin', 'Anil', 'Akil', 'Aman']}

df = pd.DataFrame(dict(zip(lst[0], lst[1:])))        

print(df)
     

<ipython-input-12-88cd59fed4cd>:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


   id name address
0   1    A   Aswin
1   2    B    Anil
2   3    C    Akil
3   4    D    Aman


In [13]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
df = pd.DataFrame(arr)
df

<class 'ValueError'>: Must pass 2-d input. shape=(1, 3, 3)

In [14]:
#DataFrame is a two-dimensional table with rows and columns only.

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [15]:
df.shape              #attribute


(3, 3)

In [16]:
#returns the index (row labels) of the DataFrame 
print(df.index)                    #attribute

RangeIndex(start=0, stop=3, step=1)


In [17]:
print(df.size)                    #attribute

9


In [18]:
data = {'Name': ['Aswin', 'Abdullah', 'Ankush'],
        'Age': [20, 30, 35],
        'City': ['Chennai', 'Kerala', 'London']}
df = pd.DataFrame(data)


df.columns               #attribute

Index(['Name', 'Age', 'City'], dtype='object')

In [19]:
#returns a list containing the row axis labels and column axis labels
#The first element represents the row index.
#The second element represents the column index with dtype.

df.axes                     #attribute

[RangeIndex(start=0, stop=3, step=1),
 Index(['Name', 'Age', 'City'], dtype='object')]

In [20]:
#returns a DataFrame of the same shape as the original, 
#but with Boolean values indicating where values in the original DataFrame are NaN

df.isna()

Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False

In [21]:
df.loc[0]            #will be a series with index as column headers

Name      Aswin
Age          20
City    Chennai
Name: 0, dtype: object

In [22]:
#df['Age'] >= 35: This creates a Boolean Series (essentially a list of True/False values)
#df[df['Age'] >= 35]: This uses the Boolean Series to filter the DataFrame. Only the rows where the condition is True.

df[df['Age'] >= 35]

Name  Age    City
2  Ankush   35  London

In [23]:
#value chage at 0th row column "age"
#.at used to get or set a single value in df 

df.at[0, 'Age'] = 26
df

Name  Age     City
0     Aswin   26  Chennai
1  Abdullah   30   Kerala
2    Ankush   35   London

In [24]:
#value_counts() function counts the occurrence of each unique value in that column and returns a Series in descending order by default

data = {'A': [1, 2, 3, 4, 5],
        'B': ['chennai', 'chandigarh', 'delhi', 'coimbatore', 'kanpur']}
df = pd.DataFrame(data)

value_counts_A = df['A'].value_counts()
print(value_counts_A)

A
1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64


In [6]:
#This method removes any rows or columns that contain missing values

#df.dropna(subset=['A','B'])  drop missing values in column A and B

import pandas as pd
data= {'A': [1, 2, None, 4, 5],
        'B': ['chennai', 'chandigarh', None, 'coimbatore', 'kanpur']}
df= pd.DataFrame(data)

df.dropna()

A           B
0  1.0     chennai
1  2.0  chandigarh
3  4.0  coimbatore
4  5.0      kanpur

In [4]:
df1 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value1': [10, 20, 30]})
df2 = pd.DataFrame({'key': ['B', 'C', 'D'], 'value2': [40, 50, 60]})

# Merge based on 'key' column
merged_df = pd.merge(df1, df2, on='key', how='inner')
print(merged_df)

  key  value1  value2
0   B      20      40
1   C      30      50


In [7]:
#df.groupby('B'): group the DataFrame df by the values in column 'B'.

#['A'].sum(): For each group created this sums up the values in column 'A'. 

#.reset_index(): reset_index() converts this multi-level index back into columns, making 'B' and 'A' regular columns again.
grouped_df = df.groupby('B')['A'].sum().reset_index()
print(grouped_df)


            B    A
0  chandigarh  2.0
1     chennai  1.0
2  coimbatore  4.0
3      kanpur  5.0


In [8]:
# Create a pivot table on the values of column A , Group by Column B, agg func (mean) on the col A.

pivot_table = df.pivot_table(values='A', index='B', aggfunc='mean')
print(pivot_table)


              A
B              
chandigarh  2.0
chennai     1.0
coimbatore  4.0
kanpur      5.0


In [9]:
def square(x):
    return x ** 2

# Apply the (any)custom function to 'A' column
df['A_squared'] = df['A'].apply(square)
print(df)

     A           B  A_squared
0  1.0     chennai        1.0
1  2.0  chandigarh        4.0
2  NaN        None        NaN
3  4.0  coimbatore       16.0
4  5.0      kanpur       25.0


In [10]:
import pandas as pd

data = {'A': [10, 20, None, 30, 40],
        'B': [None, 'chennai', 'coimbatore', 'london', 'america']}

df = pd.DataFrame(data)

df.dropna(axis=1)             #axis0 = row ; axis1 = col;

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [11]:
#In Column A fillNAN in Column A with mean of Col A , changes in original df(inplace = True)

df['A'].fillna(df['A'].mean(), inplace=True)           
df

<ipython-input-11-462b24f90d9e>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(df['A'].mean(), inplace=True)


A           B
0  10.0        None
1  20.0     chennai
2  25.0  coimbatore
3  30.0      london
4  40.0     america

In [12]:
#eg if Col A has 3 unique values and Col B has 2 uniques values others duplicates...
# The function identifies and removes any duplicate rows.
#it will drop rows where the entire row is identical to another.

df.drop_duplicates()        

A           B
0  10.0        None
1  20.0     chennai
2  25.0  coimbatore
3  30.0      london
4  40.0     america

In [3]:
import pandas as pd 

data = {'A': [1, 2, 3, 4, 5],
        'B': [' apple ', 'banana', 'cherry ', 'date', ' elderberry ']}
df = pd.DataFrame(data)

df['B'] = df['B'].str.strip()
print(df)


   A           B
0  1       apple
1  2      banana
2  3      cherry
3  4        date
4  5  elderberry


In [4]:
data = {'A': [1, 2, 3, 4, 5],
        'B': ['apple', 'banana', 'cherry', 'date', 'chocolate'],
        'C': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

# Remove the 'C' column
df.drop('C', axis=1, inplace=True)
print(df)

   A          B
0  1      apple
1  2     banana
2  3     cherry
3  4       date
4  5  chocolate


In [5]:
data = {'A': [1, 2, 3, 4, 5],
        'B': ['apple', 'banana', 'cherry', 'date', 'chocolate'],
        'C': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

# Remove the 'C' column
df.drop('C', axis=0, inplace=True)                #axis = 0 is for row , cannot delete a column by it...
print(df)

<class 'KeyError'>: "['C'] not found in axis"

In [6]:
#df['Category']: This selects the 'Category' column in your DataFrame df.

#.map(category_mapping): This method maps each value in the 'Category' column to a corresponding value in the category_mapping dictionary.

data = {'Category': ['A', 'B', 'A', 'C', 'B']}
df = pd.DataFrame(data)

category_mapping = {'A': 1, 'B': 2, 'C': 3}

df['Category_Num'] = df['Category'].map(category_mapping)
df

Category  Category_Num
0        A             1
1        B             2
2        A             1
3        C             3
4        B             2

In [7]:
#This method applies a function to every single element of the DataFrame

data = {'A': [1, 2, 3],
        'B': [4, 5, 6]}
df = pd.DataFrame(data)

def square(x):
    return x ** 2

df_squared = df.applymap(square)
print(df_squared)

<ipython-input-7-892b7902697b>:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_squared = df.applymap(square)


   A   B
0  1  16
1  4  25
2  9  36
