# NUMPY BASICS 

In [1]:
import numpy as np 

In [2]:
list1 = [10,20,30,40,50]
list1

[10, 20, 30, 40, 50]

In [7]:
arr1 = np.array([list1])         #list is considered as an element of array
arr1

array([[10, 20, 30, 40, 50]])

In [6]:
arr1 = np.array(list1)           #list is considered as array
arr1

array([10, 20, 30, 40, 50])

In [9]:
arr2 = np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [10]:
arr3 = np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [12]:
arr4 = np.random.random(5)
arr4                       # float value in the interval [0.0,1.0]

array([0.29058292, 0.20239573, 0.70995962, 0.28260315, 0.87977078])

In [16]:
A = np.array([11,34,56,67])
B = np.ones(4)
A+B            # can't do all ops once print only the last one 

array([12., 35., 57., 68.])

In [18]:
A+B , A-B , A*B , A/B , A//B

(array([12., 35., 57., 68.]),
 array([10., 33., 55., 66.]),
 array([11., 34., 56., 67.]),
 array([11., 34., 56., 67.]),
 array([11., 34., 56., 67.]))

In [4]:
import numpy as np

A = np.array([11,34,56,67])
B = np.ones(4)
A**B , B**A

(array([11., 34., 56., 67.]), array([1., 1., 1., 1.]))

In [6]:
A%B , B%A

(array([0., 0., 0., 0.]), array([1., 1., 1., 1.]))

In [7]:
arr = np.array([2,45,6,7,8])
arr*1.5

array([ 3. , 67.5,  9. , 10.5, 12. ])

In [8]:
arr + arr

array([ 4, 90, 12, 14, 16])

In [9]:
arr[0]

2

In [10]:
arr[0:4]

array([ 2, 45,  6,  7])

In [11]:
arr[0:]

array([ 2, 45,  6,  7,  8])

In [12]:
arr[:-1]

array([ 2, 45,  6,  7])

In [13]:
arr[-1:]         #only last element

array([8])

In [14]:
arr[-1:0]       #empty array 

array([], dtype=int32)

In [15]:
arr[:5]

array([ 2, 45,  6,  7,  8])

In [16]:
arr.min()

2

In [17]:
arr.max()

45

In [18]:
arr.sum()

68

In [19]:
arr.mean()

13.6

In [21]:
np.median(arr)

7.0

In [22]:
np.std(arr)

15.83161394173064

In [23]:
np.var(arr)

250.63999999999996

In [24]:
arr.argmin()

0

In [25]:
arr.argmax()

1

In [26]:
arr.prod()

30240

In [28]:
np.array([[2,3],[3,5]])

array([[2, 3],
       [3, 5]])

In [30]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.random.random((2,4))

array([[0.34256299, 0.99117281, 0.24520184, 0.54868095],
       [0.44786536, 0.59490845, 0.14188713, 0.29237441]])

In [3]:
import numpy as np
np.array([[3,2],[6,4],[7,4]])+ np.array([1,1])

array([[4, 3],
       [7, 5],
       [8, 5]])

In [4]:
np.array([[3,2],[6,4],[7,4]]) - np.array([1,1])

array([[2, 1],
       [5, 3],
       [6, 3]])

In [5]:
np.array([[3,2],[6,4],[7,4]])* np.array([1,1])

array([[3, 2],
       [6, 4],
       [7, 4]])

In [6]:
np.array([[3,2],[6,4],[7,4]])/ np.array([1,1])

array([[3., 2.],
       [6., 4.],
       [7., 4.]])

In [7]:
np.array([[3,2],[6,4],[7,4]])// np.array([1,1])

array([[3, 2],
       [6, 4],
       [7, 4]])

In [8]:
A = np.array([[3,4,5,6],[6,3,4,2],[4,3,2,1]])         #matrix 3x4
B = np.array([[2,3],[4,3],[4,5],[6,1]])               #matrix 4x2
A.dot(B)                                              #resultant matrix 3x2


array([[78, 52],
       [52, 49],
       [34, 32]])

In [10]:
A[0,3] , A[2,3] , A[2,1]

(6, 1, 3)

In [13]:
A[1:3,0:3]            #last value always excluded

array([[6, 3, 4],
       [4, 3, 2]])

In [12]:
A[:-1,:-1]

array([[3, 4, 5],
       [6, 3, 4]])

In [14]:
A[0:,0:]

array([[3, 4, 5, 6],
       [6, 3, 4, 2],
       [4, 3, 2, 1]])

In [15]:
A[:,:]

array([[3, 4, 5, 6],
       [6, 3, 4, 2],
       [4, 3, 2, 1]])

In [16]:
A[[1,2],[2,3]]

array([4, 1])

In [20]:
A[2,3]

1

In [21]:
A.max()

6

In [22]:
A.min()

1

In [23]:
A.sum()

43

In [24]:
A.max(axis=0)

array([6, 4, 5, 6])

In [25]:
A.max(axis=1)

array([6, 6, 4])

In [26]:
A.T

array([[3, 6, 4],
       [4, 3, 3],
       [5, 4, 2],
       [6, 2, 1]])

In [27]:
A.reshape(2,6)

array([[3, 4, 5, 6, 6, 3],
       [4, 2, 4, 3, 2, 1]])

In [28]:
A.reshape(1,12)

array([[3, 4, 5, 6, 6, 3, 4, 2, 4, 3, 2, 1]])

In [31]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [32]:
np.ones((2,3,1,4))

array([[[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]]])

In [33]:
np.ones((2,2,3,1,4))               #upto n-dim 
                                    #same for zeros and random 

array([[[[[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]]]],



       [[[[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]]]]])

In [35]:
np.array([ [[2,3],[3,4]] , [[5,4],[6,7]] ])        #see the syntax 

array([[[2, 3],
        [3, 4]],

       [[5, 4],
        [6, 7]]])