# NUMPY PRACTICE QUESTIONS 

In [1]:
import numpy as np

In [6]:
print(np.__version__)

1.26.4


In [3]:
np.show_config()

/lib/python3.12/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


{
  "Compilers": {
    "c": {
      "name": "emscripten",
      "linker": "ld.wasm",
      "version": "3.1.58",
      "commands": "/tmp/tmp3oeg_syr/cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.10",
      "commands": "cython"
    },
    "c++": {
      "name": "emscripten",
      "linker": "ld.wasm",
      "version": "3.1.58",
      "commands": "/tmp/tmp3oeg_syr/c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "wasm",
      "family": "wasm32",
      "endian": "little",
      "system": "emscripten"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": true
  },
  "Build Dependencies": {
    "blas": {
      "name": "auto"
    },
    "lapack": {
      "name": "dep140313304261760",
      "found": true,
      "version": "1.26.4",
      "detection method": "internal",
      "include directory": "unknown",
      "lib directory

In [7]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
python -c "import numpy; numpy.info(numpy.add)"

<class 'SyntaxError'>: invalid syntax (<ipython-input-8-1663cd30cb7c>, line 1)

In [10]:
Z= np.zeros(10)
Z[4]= 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
Z = np.arange(10,50)
Z                     #last value excluded

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
Z =np.arange(50)
Z                 #by default starts from 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
Z = np.arange(50,2)
Z

array([], dtype=int32)

In [18]:
Z = np.arange(0,10,2)
Z

array([0, 2, 4, 6, 8])

In [19]:
Z =np.arange(50)
Z=Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [20]:
Z =np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int32),)

In [23]:
Z =np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
Z =np.random.random((3,3,3))
Z

array([[[0.48504567, 0.79338442, 0.74926178],
        [0.31448724, 0.80180471, 0.14522921],
        [0.29577507, 0.33644746, 0.28481416]],

       [[0.07822632, 0.73249676, 0.88823027],
        [0.30313749, 0.56074962, 0.09083721],
        [0.62336708, 0.23135145, 0.63575549]],

       [[0.05894258, 0.6805263 , 0.23385224],
        [0.32473578, 0.60123818, 0.19739505],
        [0.58372376, 0.60277092, 0.76814591]]])

In [27]:
Z =np.random.random((10,10))
Z
Z.min(),Z.max()

(0.00931927085163986, 0.9737784893311243)

In [28]:
Z =np.random.random(30)
Z.mean()

0.5031692517642234

In [2]:
import numpy as np

Z = np.ones((10,10))
Z[1:-1,1:-1]=0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [3]:
0*np.nan

nan

In [4]:
np.nan == np.nan

False

In [5]:
np.inf > np.nan

False

In [6]:
np.nan - np.nan

nan

In [7]:
0.3 == 3*0.1

False

In [10]:
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [11]:
Z = np.diag(1+np.arange(4))
Z

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [12]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [14]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [15]:
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


In [21]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.56779227 0.90526579 0.23145222 0.50990065 0.60628853]
 [0.23017555 0.65736089 1.         0.30009561 0.25780349]
 [0.35361322 0.39108004 0.53958131 0.60721153 0.02654138]
 [0.52631158 0.55594804 0.64135355 0.69223063 0.20634561]
 [0.99781529 0.34101106 0.         0.29422342 0.84203385]]


In [23]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])

<ipython-input-23-349c455c09b5>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [24]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [26]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10
